<a href="https://colab.research.google.com/github/PrasanthTheAnalyst/ProjectProfile/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd

In [70]:
df = pd.read_csv("/content/creditcard.csv")

In [71]:
df

Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [72]:
df.drop('Time', axis = 1, inplace= True)

In [73]:
df

V1         V2        V3  ...       V28  Amount  Class
0       -1.359807  -0.072781  2.536347  ... -0.021053  149.62      0
1        1.191857   0.266151  0.166480  ...  0.014724    2.69      0
2       -1.358354  -1.340163  1.773209  ... -0.059752  378.66      0
3       -0.966272  -0.185226  1.792993  ...  0.061458  123.50      0
4       -1.158233   0.877737  1.548718  ...  0.215153   69.99      0
...           ...        ...       ...  ...       ...     ...    ...
284802 -11.881118  10.071785 -9.834783  ...  0.823731    0.77      0
284803  -0.732789  -0.055080  2.035030  ... -0.053527   24.79      0
284804   1.919565  -0.301254 -3.249640  ... -0.026561   67.88      0
284805  -0.240440   0.530483  0.702510  ...  0.104533   10.00      0
284806  -0.533413  -0.189733  0.703337  ...  0.013649  217.00      0

[284807 rows x 30 columns]

In [75]:
cases =len(df)

In [76]:
cases

284807

In [77]:
non_fraud_cases = len(df[df['Class']==0])

In [78]:
non_fraud_cases

284315

In [79]:
fraud_cases = len(df[df['Class']==1])

In [80]:
fraud_cases

492

In [81]:
fraud_percentage = round(fraud_cases/non_fraud_cases*100,2)

In [82]:
fraud_percentage

0.17

Normalizing the values

In [83]:
from sklearn.preprocessing import StandardScaler

In [84]:
sc = StandardScaler()

In [85]:
amt = df['Amount'].values

In [86]:
df['Amount'] = sc.fit_transform(amt.reshape(-1,1))

In [87]:
df['Amount'].head

<bound method NDFrame.head of 0         0.244964
1        -0.342475
2         1.160686
3         0.140534
4        -0.073403
            ...   
284802   -0.350151
284803   -0.254117
284804   -0.081839
284805   -0.313249
284806    0.514355
Name: Amount, Length: 284807, dtype: float64>

Data Training

In [91]:
x = df.drop('Class', axis=1).values
y = df['Class'].values

In [92]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [93]:
from sklearn.model_selection import train_test_split

In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

#Modeling

DecisionTree

In [96]:
from sklearn.tree import DecisionTreeClassifier

In [100]:
tree_model = DecisionTreeClassifier(max_depth= 4, random_state=1, criterion = 'entropy')

In [101]:
tree_model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [102]:
tree_pred = tree_model.predict(x_test)

KNN Algorithm

In [115]:
from sklearn.neighbors import KNeighborsClassifier

In [116]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [117]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [148]:
knn_pred = knn.predict(x_test)

Logistic Regression

In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
lr = LogisticRegression()

In [113]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [114]:
lr_pred =lr.predict(x_test)

SVM Algo

In [149]:
from sklearn.svm import SVC

In [150]:
svm = SVC()

In [ ]:
svm.fit(x_train,y_train)

In [140]:
svm_pred = svm.predict(x_test)

AttributeError: ignored

Random Forest Classifier

In [123]:
from sklearn.ensemble import RandomForestClassifier

In [124]:
rfc = RandomForestClassifier(max_depth=4)

In [125]:
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [126]:
rfc_pred = rfc.predict(x_test)

Accuracy Score & Confusion Matrics


In [142]:
from sklearn.metrics import accuracy_score, confusion_matrix

Decision Tree Accuracy score

In [133]:
accuracy_score(y_test,tree_pred)

0.9993679997191109

Decision Tree Confusion Matrix

In [143]:
confusion_matrix(y_test,tree_pred)

array([[56849,    12],
       [   24,    77]])

Knn algo accuracy score

In [ ]:
accuracy_score(y_test, knn_pred)

KNN Confusion Matrix

In [ ]:
confusion_matrix(y_test,knn_pred)

Logistic Regression Accuracy score

In [135]:
accuracy_score(y_test,lr_pred)

0.9991924440855307

Logistic regression Confusion Matrix

In [145]:
confusion_matrix(y_test,lr_pred)

array([[56852,     9],
       [   37,    64]])

SVM Accuracy score

In [136]:
accuracy_score(y_test,svm_pred)

NameError: ignored

Random forest Accuracy score

SVM Confusion Matrix

In [146]:
confusion_matrix(y_test,svm_pred)

NameError: ignored

Random forest Accuracy score

In [141]:
accuracy_score(y_test,rfc_pred)

0.9993153330290369

Random forest Confusion Matrix

In [147]:
confusion_matrix(y_test,rfc_pred)

array([[56854,     7],
       [   32,    69]])